on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    environment: Production
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        source-url: ${{ secrets.NUGET_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.READ_REPO_TOKEN }}

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --no-build